import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        display: ["Fredoka", "Nunito", "sans-serif"],
        sans: ["Nunito", "Quicksand", "system-ui", "sans-serif"],
        serif: ["Fraunces", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        baddia: {
          pink: "hsl(var(--pink-soft))",
          hot: "hsl(var(--pink-hot))",
          lavender: "hsl(var(--lavender))",
          pearl: "hsl(var(--pearl))",
          gold: "hsl(var(--gold))",
          purple: "hsl(var(--deep-purple))",
        },
        pink: {
          50: "hsl(340 100% 98%)",
          100: "hsl(340 100% 95%)",
          200: "hsl(340 100% 90%)",
          300: "hsl(340 100% 82%)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
        "4xl": "2rem",
        "5xl": "2.5rem",
      },
      backgroundImage: {
        "gradient-baddia": "var(--gradient-baddia)",
        "gradient-glow": "var(--gradient-glow)",
        "gradient-gold": "var(--gradient-gold)",
        "gradient-pearl": "var(--gradient-pearl)",
        "gradient-sky": "var(--gradient-sky)",
        "gradient-night": "var(--gradient-night)",
      },
      boxShadow: {
        soft: "0 8px 24px -8px hsl(348 80% 70% / 0.25)",
        glow: "0 12px 40px -10px hsl(348 100% 60% / 0.45)",
        card: "0 10px 30px -12px hsl(271 50% 40% / 0.18)",
        sticker: "0 6px 0 -1px hsl(348 100% 92%), 0 14px 28px -10px hsl(348 80% 60% / 0.35)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { transform: "scale(0.96)", opacity: "0" }, "100%": { transform: "scale(1)", opacity: "1" } },
        float: { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-8px)" } },
        twinkle: { "0%,100%": { opacity: "0.4", transform: "scale(0.8)" }, "50%": { opacity: "1", transform: "scale(1.15)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "spin-slow": { to: { transform: "rotate(360deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "scale-in": "scale-in 0.4s ease-out",
        float: "float 4s ease-in-out infinite",
        twinkle: "twinkle 2.4s ease-in-out infinite",
        shimmer: "shimmer 2.5s linear infinite",
        "spin-slow": "spin-slow 8s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
